$foreground = rgb(c1c2c3)
$background = rgb(080b12)
$wallpaper = rgb(home/nicojackson/Pictures/wallpapers/solidsnake.jpeg)

$color0 = rgb(080b12)
$color1 = rgb(5d5f61)
$color2 = rgb(6a6b6d)
$color3 = rgb(767778)
$color4 = rgb(838485)
$color5 = rgb(8e8f90)
$color6 = rgb(9b9b9c)
$color7 = rgb(8c9096)
$color8 = rgb(575d6a)
$color9 = rgb(7D7F82)
$color10 = rgb(8E8F92)
$color11 = rgb(9E9FA1)
$color12 = rgb(AFB0B2)
$color13 = rgb(BEBFC1)
$color14 = rgb(CFCFD0)
$color15 = rgb(c1c2c3) 
